name: Deploy to GitHub Pages

on:
  pull_request:
    branches:
      - main  # Deploy preview when PR is created against main

  push:
    branches:
      - main  # Deploy after PR is merged into main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'  # Deploy to production after merge
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Deploy PR Preview to GitHub Pages
        if: github.event_name == 'pull_request'  # Deploy preview for PRs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages-preview  # Deploy PR preview to separate branch
